### ISSUE TITLE
add default timeout value to requests in v1.x 

### ISSUE THREAD

**Issue by pecalleja** [zeyneloz/onesignal_sdk#15]
Hi,
The sdk version v1.x uses the requests library. so we need to add a default timeout value to raise a proper exception when onesignal api is down.

https://documentation.onesignal.com/docs/onesignal-api#what-is-the-response-timeout-for-api-endpoints

What is the response timeout for API endpoints?
Responses are usually generated within a couple seconds. However, in extreme cases, they can take longer.
OneSignal will wait 30 seconds for a response before automatically canceling the request. To verify no duplicate requests go through, you can add an Idempotent Key with the external_id parameter.

but in requests documentation:
https://requests.readthedocs.io/en/master/user/advanced/#timeouts

Timeouts
Most requests to external servers should have a timeout attached, in case the server is not responding in a timely manner. By default, requests do not time out unless a timeout value is set explicitly. Without a timeout, your code may hang for minutes or more.

lack of timeout param in v1.x version  👇
```python
def basic_auth_request(method, url, token=None, payload=None, params=None):
    """
    make a request using basic authorization
    :param method: [GET, POST, PUT, DELETE ...]
    :param url:
    :param token: basic authentication token
    :param payload: post body
    :param params: Dictionary or bytes to be sent in the query string
    :return:
    """
    request_kwargs = {}
    if token is not None:
        request_kwargs["headers"] = {"Authorization": "Basic {0}".format(token)}
    if payload is not None:
        request_kwargs["json"] = payload
    if params is not None:
        request_kwargs["params"] = params
    return requests.request(method, url, **request_kwargs)
```

**Comment by luk156** [comment]
the commit will be merged???

**Comment by pecalleja** [comment]
they just closed the PR without merging it 😔 🤷‍♂️
