### ISSUE TITLE
Is it possible to setEmail with this wrapper ? 

### ISSUE THREAD

**Issue by bousmahafaycal** [zeyneloz/onesignal_sdk#5]
Hello, 

Thanks for this wrapper it's useful ! I want to know how can i set an email for onesignal with this ? Is it possible ? 

Thanks,

**Comment by zeyneloz** [comment]
This is just a wrapper around official [OneSignal Web Rest Api](https://documentation.onesignal.com/reference). There is no endpoint for setting an email on this documentation, so no, it is not possible to set an email unfortunately.
