### ISSUE TITLE
Can't find user_auth_key on keys and ids tab on Onesignal website

### ISSUE THREAD

**Issue by FrancescoPaiola** [zeyneloz/onesignal_sdk#7]
Hi,
Is `user_auth_key` still needed? beacuse on Onesignal website i just found `onesignal app id` and `rest api key` in _keys and ids_ tab.

**Comment by Suryanandsingh** [comment]
Hi @FrancescoPaiola ,
Please login to OneSignal then go to **Account**  section and then scroll down there is **User Auth Key**.

Follow this: https://documentation.onesignal.com/docs/accounts-and-keys#section-user-auth-key

Thanks

**Comment by zeyneloz** [comment]
`user_auth_key` is not a required field anymore, please check the latest version of the library. Closing this issue.
