### ISSUE TITLE
OneSignal not accepting player id 'invalid_player_ids' when sending notification via REST API

### ISSUE THREAD

**Issue by ahmedsafadii** [zeyneloz/onesignal_sdk#9]
When I try to send a notification if there were invalid_player_ids in the ids, the process of sending notifications is stop, how it's possible to let the one signal ignore the invalid_player_ids?

**Comment by zeyneloz** [comment]
Hey @ahmedsafadii ,
The issue you mentioned is related to OneSignal itself but not this library. You should check onesignal documentation for the answer: https://documentation.onesignal.com/reference/create-notification#results---create-notification
My suggestion would be not sending invalid player id s in the first place and filter them beforehand.
I am closing the the issue.
